services:
  app:
    build: ./rag-demo
    container_name: ai-finance-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./rag-demo:/app

    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/finance_db
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=finance_db
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - backend

  db:
    image: pgvector/pgvector:pg16
    container_name: ai-finance-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=finance_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6-alpine
    container_name: ai-finance-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redisdata:/data
    networks:
      - backend

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: ai-finance-redis-commander
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - backend

volumes:
  pgdata:
  redisdata:

networks:
  backend:
    driver: bridge
